<?php
/**
 * Created by JetBrains PhpStorm.
 * User: kavinga
 * Date: 10/27/13
 * Time: 8:54 PM
 * To change this template use File | Settings | File Templates.
 */
?>

<table width="100%" cellspacing="2" cellpadding="5" border="1"
       style="border-color:#fcfcda;background:#f6ff00;" class="">
    <tbody>
    <tr>
        <td align="center" colspan="4"><b style="font-size:18px;">NOTIFICATION OF COMMUNICABLE
                DISEASE</b></td>
    </tr>
    <tr>
        <td width="100" align="right">Institute:</td>
        <td align="left"><?php echo $hospital->Name ?></td>
        <td width="150" align="right">Disease:</td>
        <td align="left"><?php echo $notification->Disease ?>
        </td>
    </tr>
    <tr>
        <td align="right">Name of patient:</td>
        <td align="left"><?php echo
                $patient->Personal_Title . ' ' . $patient->Full_Name_Registered . ' ('
                . $patient->HIN . ')' ?></td>
        <td align="right">Date of Onset:</td>
        <td align="left">-</td>
    </tr>
    <tr>
        <td align="right">Guardian:</td>
        <td align="left">-</td>
        <?php if ($epicode_type == "Admission") {
            echo
                "<td  align='right'>Date of Admission:</td><td  align='left' >"
                . $epicode->getValue("AdmissionDate") . "</td>";
        } ?>
    </tr>
    <tr>
        <td colspan="4">
            <table width="100%" cellspacing="0" cellpadding="5" border="0" class="PrescriptionInfo">
                <tbody>
                <tr>
                    <?php

                    if ($epicode_type == "Admission") {
                        echo "<td align='right'  nowrap>BHT No"
                            . ":</td><td align='left' nowrap>" . $epicode->getValue("BHT")
                            . "</td>";
                        echo "<td align='right'  nowrap>Ward"
                            . ":</td><td align='left' nowrap>" . $ward->getValue("Name")
                            . "</td>";
                    } else {
                        if ($epicode_type == "Opd") {
                            echo "<td align='right'  nowrap>Ward"
                                . ":</td><td align='left' nowrap>OPD</td>";
                        }
                    }
                    ?>
                    <td nowrap="" align="right">Age:</td>
                    <td nowrap="" align="left"><?php echo $patient->getAge(); ?> </td>
                    <td nowrap="" align="right">Sex:</td>
                    <td nowrap="" align="left"><?php echo $patient->Gender ?></td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    <tr>
        <td width="156" nowrap="" align="right">Laboratory Results:</td>
        <td align="left"><?php echo $lab ?></td>
        <td align="right">
							Confirmed:
							</td>
                            <td align="left">
							<?php 
		
								echo $Confirmed;
							?>
							</td>
    </tr>
    <tr>
        <td width="100" align="right">Home Address:</td>
        <td align="left" colspan="3"><?php echo $patient->getAddress(); ?>
        </td>
    </tr>
    <tr>
        <td width="100" nowrap="" align="right">Patient's Home Telephone:</td>
        <td align="left" colspan="3"><?php echo $patient->Telephone ?></td>
    </tr>
    <tr>
        <td width="100" nowrap="" align="right">Remarks:</td>
        <td align="left" colspan="3"><?php echo $patient->Remarks ?></td>
    </tr>
    <tr>
        <td width="100" nowrap="" align="right">Date of Notification:</td>
        <td align="left" colspan="3"><?php echo date(DATE_RFC822) ?></td>
    </tr>
    <tr>
        <td align="left" colspan="4">Notification Confirmed by: <?php echo
                $doctor->Title . ' ' . $doctor->FirstName . ' ' . $doctor->OtherName; ?>, Sent By:
            <?php echo $user->Title . ' ' . $user->FirstName . ' ' . $user->OtherName; ?><br><i>Automatically
                generated by HHMIS patient record database
                system. </i></td>
    </tr>
    </tbody>
</table>
